"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Headphones, Play, Star } from "lucide-react";
import { useAudio } from "@/context/AudioContext";
type Track = { id: string; title: string; note?: string | null; timeTag?: string | null; url: string; playCount: number; averageRating: number; ratingCount: number };
export default function RelaxationLibrary() {
  const [tracks, setTracks] = useState<Track[]>([]); const router = useRouter(); const { playSpot } = useAudio();
  useEffect(() => { void fetch("/api/relaxation").then((r) => r.json()).then((d) => setTracks(d.data ?? [])).catch(() => undefined); }, []);
  if (!tracks.length) return null;
  const rate = async (track: Track, score: number) => { const r = await fetch("/api/relaxation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "rate", assetId: track.id, score }) }); if (r.status === 401) { window.alert("กรุณาเข้าสู่ระบบก่อนให้คะแนนเพลง"); router.push("/login?next=/"); return; } const d = await r.json(); if (d.success) setTracks((p) => p.map((x) => x.id === track.id ? { ...x, averageRating: d.averageRating, ratingCount: d.ratingCount } : x)); };
  return <section className="glass-panel rounded-3xl p-5 sm:p-6"><div className="mb-4 flex items-center gap-3"><div className="rounded-2xl bg-fuchsia-500/15 p-2.5 text-fuchsia-300"><Headphones className="h-5 w-5" /></div><div><h2 className="text-lg font-black">คลังเพลงผ่อนคลาย</h2><p className="text-xs text-foreground/60">เพลงที่แอดมินคัดเลือกสำหรับอ่านหนังสือและพักใจ</p></div></div><div className="grid gap-3 sm:grid-cols-2">{tracks.map((track) => <article key={track.id} className="rounded-2xl border border-purple-500/20 bg-purple-950/20 p-3"><div className="flex items-center gap-3"><button type="button" onClick={() => { playSpot({ id: track.id, title: track.title, subtitle: track.note ?? "เสียงผ่อนคลาย", category: "Relaxation", audioUrl: track.url }); void fetch("/api/relaxation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "play", assetId: track.id }) }); }} className="grid h-11 w-11 shrink-0 place-items-center rounded-full purple-gradient-btn"><Play className="h-4 w-4 fill-current" /></button><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold">{track.title}</h3><p className="truncate text-xs text-foreground/60">{track.note || "เสียงผ่อนคลาย"}</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[11px] text-foreground/60"><span>ฟัง {track.playCount} ครั้ง</span>{track.timeTag && <span>• {track.timeTag}</span>}<span className="ml-auto inline-flex items-center gap-1 text-amber-300"><Star className="h-3 w-3 fill-current" /> {track.averageRating.toFixed(1)} ({track.ratingCount})</span></div><div className="mt-2 flex gap-1">{[1,2,3,4,5].map((score) => <button key={score} type="button" onClick={() => void rate(track, score)} aria-label={`ให้คะแนน ${score} ดาว`} className="text-amber-300/60 hover:text-amber-300"><Star className="h-4 w-4 fill-current" /></button>)}</div></article>)}</div></section>;
}
